return {
  BACKGROUND_GROUPS = {
    "Normal",
    "NormalNC",
    "SignColumn",
    "FoldColumn",
    "LineNr",
    "EndOfBuffer",
    "StatusLine",
    "StatusLineNC",
    "TabLine",
    "TabLineFill",
    "TabLineSel",
    "WinBar",
    "WinBarNC",
    "VertSplit",
    "WinSeparator",
  },

  FLOAT_GROUPS = {
    "NormalFloat",
    "FloatBorder",
    "FloatTitle",
    "FloatFooter",
    "FloatShadow",
    "FloatShadowThrough",
    "WhichKeyFloat",
    "NotifyBackground",
    "NoicePopup",
    "NoiceConfirm",
    "TelescopeNormal",
    "TelescopeBorder",
    "TelescopePromptNormal",
    "TelescopePromptBorder",
    "TelescopePromptPrefix",
    "TelescopePromptCounter",
    "TelescopePreviewTitle",
    "TelescopeResultsTitle",
    "TelescopeSelection",
    "TelescopeSelectionCaret",
    "Pmenu",
    "PmenuBorder",
    "PmenuKind",
    "PmenuExtra",
  },

  -- base16 does not define these; blink cmdline path completions use them for icons
  BLINK_KIND_GROUPS = {
    BlinkCmpKindFile = "base08",
    BlinkCmpKindFolder = "base0A",
  },

  CATPPUCCIN_BLINK_KIND_GROUPS = {
    BlinkCmpKindFile = "red",
    BlinkCmpKindFolder = "peach",
  },

  FLOAT_PATTERNS = {
    "^Telescope",
    "^Snacks",
    "^Oil",
    "^Blink",
    "^Cmp",
  },

  BACKGROUND_PATTERNS = {
    "^BufferLine",
    "^NeoTree",
    "^NvimTree",
    "^Mason",
    "^Lazy",
    "^GitSigns",
    "^GitGutter",
    "^lualine_.*_diff_",
  },

  DIFF_GROUPS = {
    "DiffAdd",
    "DiffChange",
    "DiffDelete",
    "DiffText",
    "DiffTextAdd",
    "DiffAdded",
    "DiffRemoved",
    "DiffFile",
    "DiffNewFile",
    "DiffLine",
  },
}
